import {
  JACKPOT_SEQUENCE_START_DELAY_MS,
  LEGENDARY_JACKPOT_SEQUENCE_DURATION_MS,
  LEGENDARY_JACKPOT_SEQUENCE_FADE_OUT_MS,
  LEGENDARY_JACKPOT_SEQUENCE_HOLD_MS,
  WIN_CELEBRATION_DURATIONS_MS,
  type WinCelebrationTier,
} from "./winCelebrationEffects";

export const WIN_IMAGE_WIDTH = 520;
export const LEGENDARY_JACKPOT_MUSIC_DUCK_DURATION_MS =
  JACKPOT_SEQUENCE_START_DELAY_MS +
  LEGENDARY_JACKPOT_SEQUENCE_DURATION_MS +
  LEGENDARY_JACKPOT_SEQUENCE_HOLD_MS +
  LEGENDARY_JACKPOT_SEQUENCE_FADE_OUT_MS;
export const WIN_CELEBRATION_MUSIC_DUCK_DURATIONS_MS: Record<WinCelebrationTier, number> = {
  win: WIN_CELEBRATION_DURATIONS_MS.win,
  bigWin: WIN_CELEBRATION_DURATIONS_MS.bigWin,
  jackpot: WIN_CELEBRATION_DURATIONS_MS.jackpot,
};
export const GOLD_NUMBER_FONT_FACE = "SlotGameKitGold";
