import type { AudioEventId } from "../types/asset.types";

export const AUDIO_CONFIG = {
  manifestPath: "/assets-v2/audio/manifest.json",
  runtimeFormats: ["wav", "mp3"],
  placeholderFormat: "wav",
  localStorageKeys: {
    musicMuted: "elgallero.audio.musicMuted",
    sfxMuted: "elgallero.audio.sfxMuted",
  },
  events: [
    "button",
    "toggleOff",
    "bet",
    "spin",
    "slotReel",
    "reelStop",
    "reelStop1",
    "reelStop2",
    "reelStop3",
    "reelStop4",
    "reelStop5",
    "slotLose1",
    "slotLose2",
    "tick",
    "cascade",
    "win",
    "smallWin",
    "bigWin",
    "megaWin",
    "jackpot",
    "legendaryJackpot",
    "fireworks",
    "refill",
    "wildExpand",
    "wildSymbol",
    "scatterTease",
    "paylineTrace",
    "coinPop",
    "cascadeImpact",
    "cascadeChain",
    "freeSpinAward",
    "nearMiss",
    "gridPulse",
  ] satisfies AudioEventId[],
} as const;
